# 15 Dec 2020 09:07
About org-latex-compile-with-template 

* Purpose: Simplify the customization of Latex export from Org mode

The function =org-latex-compile-with-template= implements an alternative way to turn an org-mode buffer or subtree into latex and compile it into pdf.  It is part of a collection of functions, which provide utilities for customizing the header and footer parts of the latex file, in order to produce output in different styles and with different options. 
* Pdflatex vs. xelatex
=org-latex-compile-with-template= provides choices for compiling with =pdflatex= and =xelatex=.  =XeLaTex= is more suitable for compiling buffers that use custom fonts (not part of the Tex, but installed on your current computer), and for texts written in multiple languages (especially non-latin-character-set languages, such as Greek, Chinese, Japanese, Korean, etc.), using UTF-8. The present packages provides provides keybindings for choosing whether to use =pdflatex= or =xelatex=.

* hydra keyboard menu interface
These functions can be called from a menu provided by a =hydra=.  The hydra (=hydra-latex/body=) is bound to the keyboard shortcut =Control-Meta-Shift-l=. The key bindings are: 

** "x" org-xelatex-compile-buffer "ORG xelatex buffer

Compile entire buffer using xelatex.  Xelatex 

** "X" org-xelatex-compile-subtree "ORG xelatex subtree
** "l" pdflatex-compile-buffer "TEX pdflatex buffer
** "L" xelatex-compile-buffer "TEX xelatex buffer
** "p" org-pdflatex-compile-buffer "ORG pdflatex buffer
** "P" org-pdflatex-compile-subtree "ORG pdflatex subtree
** "t" org-latex-set-buffer-template-interactively "set buffer template
** "T" org-latex-set-subtree-template-interactively "set subtree template
** "/" org-latex-post-file-template-path "post file template path
** "?" org-latex-post-subtree-template-path "post subtree template path
** "f" org-latex-find-file-template-file "find file template file
** "F" org-latex-find-subtree-template-file "find subtree template file
** "K" kill-latex-process-buffer "kill latex process buffer" :exit 
** "q" quit "exit hydra"

* How it Works

The main function for compiling, =org-latex-compile-with-template=  provides an alternative way to export the current buffer or subtree as latex. This function gets the header and footer for the latex file from a template file written in =LaTeX=. It does not use any header from org-mode options.  Using a template file instead of writing the org-mode options in emacs-lisp makes it easier to edit and try out headers.



** Export steps (for function =org-latex-compile-with-template=)

***  Step 1: Convert org-mode to latex
   
This is done in function =org-latex-compile-with-template= by the following function call:

#+begin_src elisp
(org-export-as
;; backend subtreep visible-only body-only ext-plist
     'latex   subtreep   nil       t         nil)
#+end_src

The arguments provided to =org-export-as= work as follows:

- ='latex= signals to output as latex
- If =subtreep= is non-nil (=t=), then export only the current subtree.  Else if it is nil, then export the entire buffer.
- =visible-only= is set to =nil=, and signals to export the entire contents of the subtree or buffer.  (Parts hidden by the user are also exported).
- body-only set to =t=: Export only the org-mode text contents. Do not include header or footer option settings.
- ext-plist set to =nil=: No other customization properties are provided.

*** Step 2: save latex to file

Step 1 converts the selected part of the org-mode buffer to latex. The resulting latex code is saved to file =body.tex= inside the templates directory.  This directory is obtained by function like this:

#+begin_src elisp
  (let*
      ((template-path (if subtreep
                          (org-latex-get-subtree-template-path)
                        (org-latex-get-file-template-path)))
       (template-directory (file-name-directory template-path))
     ;;; ...
       (body-path (concat template-directory "body.tex"))))
#+end_src
 =org-latex-

**** test: 

#+begin_src emacs-lisp
(org-latex-get-subtree-template-path)
#+end_src

#+RESULTS:
: /home/iani/latex-exports/templates/000BASIC/framework.tex

*** Step 3: get framework file
**** 3.1 Get path of framework file
Get path from global property if exporting entire buffer or subtree property if exporting subtree.  The code for this is: 

#+begin_src emacs-lisp
(if subtreep
                          (org-latex-get-subtree-template-path)
                        (org-latex-get-file-template-path))
#+end_src


Example 1: Getting the default framework path (no framework was specified by the user in the buffer).  In this case, both the subtree and file template path point to the same path, as shown here:
 
**** subtree template path

#+begin_src emacs-lisp
(org-latex-get-subtree-template-path)
#+end_src

#+RESULTS:
: /home/iani/latex-exports/templates/000BASIC/framework.tex


#+begin_src emacs-lisp

#+end_src

**** file template path

#+begin_src emacs-lisp
(org-latex-get-file-template-path)
#+end_src

#+RESULTS:
: /home/iani/latex-exports/templates/000BASIC/framework.tex

Example 2: Setting a custom framework for a subtree:

**** subtree with custom framework
     :PROPERTIES:
     :DATE:     <2020-12-19 Sat 15:30>
     :LATEX_HEADER_PATH: /home/iani/latex-exports/templates/000BASIC/history/00verysimple201210_201214.tex
     :END:

The custom framework path for this subtree was set interactively with function =org-latex-set-subtree-template-interactively=.  After that, the template path was tested like this:

#+begin_src emacs-lisp
(org-latex-get-subtree-template-path)
#+end_src

#+RESULTS:
: /home/iani/latex-exports/templates/000BASIC/history/00verysimple201210_201214.tex

**** Copy framework file to =<templatefolder>/framework.tex=

In order to use the selected framework for compiling into pdf, it is necessary to copy that framework into the same folder where the =body.tex= file is to be exported, so that the framework file finds the body file.  Therefore, before compiling to pdf, one must do this: 

Copy the selected framework template file into =(concat template-directory "framework.tex")=. Like this:

#+begin_src emacs-lisp
(file-copy template-path (concat template-directory "framework.tex"))
#+end_src


*** Step 4: Compile framework + exported body

*** Step 5: Copy framework as backup

Copy =<templatefolder>/framework.tex= to =<templatefolder>/history/<exportname>.tex= 

<exportname> is 

*** Step 6: Save link to framework backup in org-mode buffer

This is important so that when recompiling the buffer or subtree, the same framework is used.  In this way, corrections to the org-mode can be made at any time later on, and re-exported to pdf while keeping the same latex options defined in the framework.

* Variables

** =org-latex-export-path=

The variable =org-latex-export-path= 

** =org-latex-bib-folder=

** =org-latex-bib-filename=

* Functions
** =org-latex-bib-full-path=


** =org-latex-default-template-path=



** =org-latex-body-path=

** =org-pdflatex-compile-buffer=

** =org-xelatex-compile-buffer=

** =org-latex-compile-with-template=

** =xelatex-compile-buffer=

** =pdflatex-compile-buffer=

** =latex-compile-file-with-latexmk=

** =org-latex-post-file-template-path=

** =org-latex-get-file-template-path=
   :PROPERTIES:
   :DATE:     <2020-12-19 Sat 13:57>
   :END:


** =org-latex-get-subtree-template-path=

** =org-latex-set-subtree-template-interactively=

** =org-latex-set-subtree-template=

** =org-latex-read-template-path=

** =org-latex-set-buffer-template-interactively=

** =org-latex-set-buffer-template=

** =org-latex-set-buffer-export-name=

** =org-latex-set-subtree-export-name=

** =org-set-subtree-or-buffer-property=

** =org-get-custom-property=

** =org-latex-find-file-template-file=

** =org-latex-find-subtree-template-file=



** =kill-latex-process-buffer=

Interactive. Utility for killing the process buffer that displays the pdf preview (=epdfview=).  This closes the pdf preview window and and frees the buffer for then next preview.
