# 24 Mar 2021 10:21
* Paths and path components for compiling
** Summary

There is one custom variable: org-latex-base. It stores the path of the folder containing all files used to customize latex export and store the resulting pdf files.

There is one function for obtaining the name of the template to use from the exported file or subtree: org-latex-selected-template

There are are 4 functions for obtaining the paths of following directories:

1. org-latex-compile-dir = org-latex-base ++ "compile_framework"
2. org-latex-exports-dir = org-latex-base ++ "exports"
3. org-latex-templates-dir = org-latex-base ++ "templates"
4. org-latex-selected-template-path = org-latex-templates ++ org-latex-selected-template

See next section, [[*Details][Details]], for explanations of how the above folders are used. 

** Details

*** org-latex-base : Basic directory (contains all other directories)
 
org-latex-base is a custom variable.

Its default value is "~/latex-exports".

It points to the folder which contains the folders and files for compiling org-mode with a custom template, that is, the templates for choosing a custom look, the compile directory for compiling from org to pdf via latex, and the exports directory which stores all pdf's produced by the user calling org-latex-compile-with-framework.

*** org-latex-compile-dir : used to compile the exported latex to pdf

The value of =org-latex-compile-dir= is computed by a function which concatenates =org-latex-base= with ="compile_framework"=.

*** org-latex-exports-dir : compiled pdf files are copied to this directory.

function: concatenate org-latex-base with "exports"

*** org-latex-templates-dir : contains all templates as subdirectories

function: concatenate org-latex-base with "templates"

*** org-latex-selected-template : name of directory to use as template.

function: obtain from file or subtree property "LATEX_TEMPLATE"

defaults to "default_framework"

*** org-latex-selected-template-path : path of template directory

function: concatenate org-latex-templates-dir with selected-template

The template is linked (or copied?) from this path to org-latex-compile-dir


* Auxiliary help functions for getting properties from file

** org-latex-get-file-template-name :
Get template name from file property

** org-latex-get-subtree-template-name :
Get template name from subtree property

* Usage / API 

** Customization, parameters
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

- Custom variable =org-latex-base= (customizable with interactive function =customize-variable=). Default: =~/latex-exports". Directory containing template files for compiling to pdf as well as the exported pdfs.
- File or subtree property =org-latex-selected-template=. Contains the name of the directory of the template to use.  The directory must be a subdirectory of =org-latex-templates-dir= (see above under [[*Paths and path components for compiling][Paths and path components for compiling]]). Default: ="default_framework"=.
- File or subtree property =org-latex-compiler=.  Specifies the latex compiler to be used for pdf.  Suggested values: =xelatex= or =pdflatex=.  Default value: =xelatex=. 

** Main function (interactive):  =org-compile-latex-with-custom-framework=
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

Main function: =org-compile-latex-with-custom-framework=

Argument: =entirefilep=. (P - interactive with prefix)
If not nil, compile entire file. Else compile subtree.

Keyboard shortcut to be provided via hydra-latex/body =C-M-S-l=, then =l=.

** =hydra-latex/body= (redo)
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

Keyboard shortcut for =hydra-latex/body= : =C-M-S-l=

