# 24 Mar 2021 10:21
* Overview
  :PROPERTIES:
  :DATE:     <2021-05-09 Sun 06:37>
  :END:

The main function that compiles a file or subtree into pdf via latex is =org-compile-latex-with-custom-framework=.  This function uses one directory called =latex-exports=.  Inside =latex-exports= are three subdirectories:

1. =exports= : pdf files generated by =org-compile-latex-with-custom-framework= are stored here.
2. =templates= : contains subdirectories which hold the template files used by to create pdf documents in different styles.
3. =compile_framework= : Copy of one of the subdirectories from =templates=.  =org-compile-latex-with-custom-framework= makes this copy and uses it to compile pdf.

* Getting the required paths

Following are the variables and functions used to get the paths of the folders used by =org-compile-latex-with-custom-framework=.

**  Custom variable:  =org-latex-base=

=org-compile-latex-with-custom-framework= uses the custom variable =org-latex-base= as base for computing the required paths

Its default value is =~/latex-exports=.

** 3 Functions: =org-latex-exports-dir=, =org-latex-templates-dir=, =org-latex-compile-dir=

These 3 functions compute the actual paths of the =exports=, =templates= and =compile_framework= directories as follows: 

1. org-latex-exports-dir = org-latex-base ++ "exports"
2. org-latex-templates-dir = org-latex-base ++ "templates"
3. org-latex-compile-dir = org-latex-base ++ "compile_framework"

** Function =org-latex-selected-template-path=

This computes the full path of the template directory. 

org-latex-selected-template-path = org-latex-templates ++ org-latex-selected-template (see below)

=org-compile-latex-with-custom-framework= copies the directory =org-latex-selected-template-path= to =org-latex-compile-dir= and then uses the copied directory to compile the required document to pdf.

** Function =org-latex-selected-template=

This gets the name of the directory to use as template from the value stored in the property =LATEX-TEMPLATE= in the file or section that is being compiled.  The value defaults to =default-template=.

** Function =org-get-file-property=

Used to get the value of file property =LATEX-TEMPLATE=.

** Function =org-latex-copy-selected-template=

Copies the selected template to =org-latex-compile-dir=.

* Usage / API 

** Main function (interactive):  =org-compile-latex-with-custom-framework=
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

Main function: =org-compile-latex-with-custom-framework=

Argument: =entirefilep=. (P - interactive with prefix)
If not nil, compile entire file. Else compile subtree.

Keyboard shortcut =C-M-S-c=.

** Customization, parameters
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

- Custom variable =org-latex-base= (customizable with interactive function =customize-variable=). Default: =~/latex-exports=. Directory containing template files for compiling to pdf as well as the exported pdfs.
- File or subtree property =org-latex-selected-template=. Contains the name of the directory of the template to use.  The directory must exist as a subdirectory of =org-latex-templates-dir=. Default: ="default-template"=.
- File or subtree property =org-latex-compiler=.  Specifies the latex compiler to be used for pdf.  Suggested values: =xelatex= or =pdflatex=.  Default value: =xelatex=. 

** =hydra-latex/body= (redo)
   :PROPERTIES:
   :DATE:     <2021-03-25 Thu 08:19>
   :END:

Keyboard shortcut for =hydra-latex/body= : =C-M-S-l=

* outline of =org-compile-latex-with-custom-framework= 

** copy selected template to =compile-framework=

*** Calculate path of custom framework folder

*** Copy custom framework folder to =compile-framework=

** generate latex from org

** save latex to file

** compile latex to pdf

** copy pdf to exports folder

** open pdf for viewing
